# Generated by Django 4.2.6 on 2023-10-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(max_length=264)),
                ('dealer_name', models.CharField(max_length=264)),
                ('dealer_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=264)),
                ('property_location', models.CharField(max_length=264)),
                ('special_feature', models.CharField(max_length=264)),
                ('property_price', models.CharField(max_length=264)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='realapp.type')),
            ],
        ),
    ]
